repos:
  - repo: local
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
        entry: python scripts/pre_commit_hooks/trailing_whitespace.py
        language: system
        types: [text]
      - id: end-of-file-fixer
        name: end-of-file-fixer
        entry: python scripts/pre_commit_hooks/end_of_file_fixer.py
        language: system
        types: [text]
      - id: check-yaml
        name: check-yaml
        entry: python scripts/pre_commit_hooks/check_yaml.py
        language: system
        files: \.ya?ml$
      - id: check-added-large-files
        name: check-added-large-files
        entry: python scripts/pre_commit_hooks/check_added_large_files.py
        language: system
        stages: [commit]
      - id: black
        name: black
        entry: python -m black
        language: system
        types_or: [python]
        args: ["--line-length=88"]
