<?xml version="1.0"?>
<package format="3">
  <name>racetracker_perception</name>
  <version>0.1.0</version>
  <description>Race Master Pro ROS2 perception node package.</description>
  <maintainer email="devnull@example.com">Race Master Pro</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
